name: Deploy to Production

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          # Add commands to build and test your website release
          ls
          echo ">>> ${{ secrets.GITTOKEN }}"
      - name: Deploy to Production
        uses: ad-m/github-push-action
        with:
          branch: main
          repository: FreieBildung/FreieBildung.github.io
          github_token: ${{ secrets.GITTOKEN }}
    permissions:
      deployments: write
      pull-requests: write
      pages: write

